// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDVD6ka6rIXKNBTdAi3-s496DKMv0ZiA',
    appId: '1:847957729520:web:6a702e5c7414c3904b6235',
    messagingSenderId: '847957729520',
    projectId: 'chat-app-32fdb',
    authDomain: 'chat-app-32fdb.firebaseapp.com',
    storageBucket: 'chat-app-32fdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSAT7UYeC4VXOGpozu6BcBEw8Br-HfVk',
    appId: '1:847957729520:android:ec40488022be36ae4b6235',
    messagingSenderId: '847957729520',
    projectId: 'chat-app-32fdb',
    storageBucket: 'chat-app-32fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNAGXfkMzrE6Tcjc9E2IgRY_CtqbWTImo',
    appId: '1:847957729520:ios:0cd74300f541f9734b6235',
    messagingSenderId: '847957729520',
    projectId: 'chat-app-32fdb',
    storageBucket: 'chat-app-32fdb.appspot.com',
    iosClientId: '847957729520-nvke5btpr1mm9i8ctd8t8n3b236jeokh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNAGXfkMzrE6Tcjc9E2IgRY_CtqbWTImo',
    appId: '1:847957729520:ios:0cd74300f541f9734b6235',
    messagingSenderId: '847957729520',
    projectId: 'chat-app-32fdb',
    storageBucket: 'chat-app-32fdb.appspot.com',
    iosClientId: '847957729520-nvke5btpr1mm9i8ctd8t8n3b236jeokh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapplication',
  );
}
